// Runs in the page's MAIN execution world. VAHAN creates the Excel file as a
// blob URL and can revoke that URL immediately after anchor.click(). Capture
// it here, before the page has a chance to revoke it, then bridge the data URL
// to the isolated content script. The native browser download is suppressed:
// the captured bytes are uploaded to the API server instead of also landing
// in the user's local Downloads folder.
(function () {
  const originalClick = HTMLAnchorElement.prototype.click;
  const originalCreateObjectURL = URL.createObjectURL.bind(URL);
  const originalRevokeObjectURL = URL.revokeObjectURL.bind(URL);
  const blobByUrl = new Map();
  const pendingBlobUrls = new Set();
  const deferredRevokes = new Set();

  const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  const isExcelHref = (href) => Boolean(
    href && (href.startsWith("blob:") || href.includes(".xls") || href.includes("report")),
  );

  function blobToDataUrl(blob) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onerror = () => reject(reader.error || new Error("Could not read the Excel blob."));
      reader.onload = () => resolve(reader.result);
      reader.readAsDataURL(blob);
    });
  }

  async function captureAndBridge(href, fileName) {
    if (pendingBlobUrls.has(href)) return;
    pendingBlobUrls.add(href);
    let lastError;
    try {
      // A freshly-created blob can need one event-loop turn before fetch sees
      // its bytes. Retry a few times, but never bridge an empty data URL.
      for (let attempt = 0; attempt < 5; attempt += 1) {
        try {
          let blob = blobByUrl.get(href);
          if (!blob) {
            const response = await fetch(href);
            if (!response.ok) throw new Error(`Excel blob fetch failed (${response.status}).`);
            blob = await response.blob();
          }
          if (!blob.size) throw new Error("Excel blob was empty.");
          const dataUrl = await blobToDataUrl(blob);
          window.dispatchEvent(new CustomEvent("__VAHAN_EXCEL_EXPORT__", {
            detail: { dataUrl, fileName },
          }));
          return;
        } catch (error) {
          lastError = error;
          if (attempt < 4) await delay(100 * (attempt + 1));
        }
      }
      window.dispatchEvent(new CustomEvent("__VAHAN_EXCEL_EXPORT_ERROR__", {
        detail: { href, fileName, error: lastError?.message || "Excel blob was empty." },
      }));
    } finally {
      pendingBlobUrls.delete(href);
      blobByUrl.delete(href);
      if (deferredRevokes.delete(href)) originalRevokeObjectURL(href);
    }
  }

  // Keep a reference to the exact bytes generated by SheetJS. This avoids
  // re-fetching a blob URL after the page has started its download cleanup.
  URL.createObjectURL = function patchedCreateObjectURL(blob) {
    const url = originalCreateObjectURL(blob);
    if (blob instanceof Blob) {
      blobByUrl.set(url, blob);
      window.setTimeout(() => {
        if (blobByUrl.get(url) === blob) blobByUrl.delete(url);
      }, 120_000);
    }
    return url;
  };

  // SheetJS commonly calls URL.revokeObjectURL immediately after click().
  // Keep only the URL currently being captured alive; all other page URLs
  // retain their normal lifecycle.
  URL.revokeObjectURL = function patchedRevokeObjectURL(url) {
    if (pendingBlobUrls.has(url)) {
      deferredRevokes.add(url);
      return;
    }
    blobByUrl.delete(url);
    return originalRevokeObjectURL(url);
  };

  HTMLAnchorElement.prototype.click = function patchedClick() {
    if (this.hasAttribute("download")) {
      const href = this.getAttribute("href") || this.href;
      if (isExcelHref(href)) {
        captureAndBridge(href, this.getAttribute("download") || "report.xlsx");
        // Suppress the native browser download; the bridge above uploads the
        // exact bytes to the API server instead.
        return;
      }
    }
    return originalClick.call(this);
  };

  // Cover code that dispatches a synthetic click event instead of invoking
  // HTMLAnchorElement.click(). Cancel the event so Chrome never starts the
  // native download; the bridge above carries the bytes to the server.
  document.addEventListener("click", (event) => {
    const anchor = event.target?.closest?.("a[download]");
    if (!anchor) return;
    const href = anchor.getAttribute("href") || anchor.href;
    if (isExcelHref(href)) {
      event.preventDefault();
      event.stopPropagation();
      event.stopImmediatePropagation();
      captureAndBridge(href, anchor.getAttribute("download") || "report.xlsx");
    }
  }, true);
})();
